
function html = index(request,opts)
    %% html = INDEX(request,opts)
    % default index webpage for the webserver
    % see also web_close
    %          web_default
    %          web_reply
    %          web_browser
    %          web_example

    %% warnings
    %#ok<*INUSD>

    %% function
    html = ['<html>',10,...
            '',10,...
            '  <head>',10,...
            '  </head>',10,...
            '',10,...
            '  <body>',10,...
            '    <p> Matlab Server default website </p>',10,...
            '    <p> This file is located in: "',pwd(),'" </p>',10,...
            '  </body>',10,...
            '',10,...
            '</html>',10,...
            ];
end