% ANALYSIS internal script

%% gui
classdef analysis_gfx_axis < handle
    %% properties
    properties
        analysis
        position
        size
        panel
        objects
    end
    
    %% methods
    methods
        %% constructor
        function obj = analysis_gfx_axis(a)
            obj.analysis = a;
            obj.set_position([0,0]);
            obj.set_size(a);
            obj.create_panel(a);
            obj.create_objects(a);
        end
        
        %% set position
        function set_position(obj,position)
            obj.position = position;
            if ~isempty(obj.panel)
                set(obj.panel,'Position',[obj.position obj.size]);
            end
        end
        
        %% set size
        function set_size(obj,a)
            obj.size     = [    a.par.win_size(1),...
                                a.par.size_panellabel + 6*a.par.size_label(2) + 7*a.par.size_space];
        end
        
        %% create panel
        function create_panel(obj,a)
            obj.panel = uipanel(...
                'Parent',a.gfx.window.window,...
                'Title',' AXIS ',...
                'BackgroundColor',a.par.win_background,...
                'Units','pixels',...
                'Position',[obj.position obj.size]);
        end
        
        %% create objects
        function create_objects(obj,a)
            obj.objects = struct();

% hxlabel
% hylabel
  
            %% title
            item_size = [   obj.size(1)-2*a.par.size_space...
                            a.par.size_label(2) ];
            item_pos =  [   a.par.size_space...
                            obj.size(2)-a.par.size_panellabel-a.par.size_space-item_size(2)];
            obj.objects.title = uicontrol(...
                'Parent',   obj.panel,...
                'Style',    'edit',...
                'Units',    'pixel',...
                'Position', [item_pos item_size],...
                'String',   {''});
            
            %% tick
            item_size = a.par.size_label;
            item_pos  = [   a.par.size_space...
                            item_pos(2) - a.par.size_space-a.par.size_label(2) ];
            obj.objects.tick = uicontrol(...
                'Parent',obj.panel,...
                'BackgroundColor',a.par.win_background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'tick');

            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            item_size(1) = 0.5 * (obj.size(1) - item_pos(1) - 2*a.par.size_space);
            obj.objects.xtick = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String', {' '});
            
            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            obj.objects.ytick = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String', {' '});
            
            %% tick label
            item_size = a.par.size_label;
            item_pos  = [   a.par.size_space...
                            item_pos(2) - a.par.size_space-a.par.size_label(2) ];
            obj.objects.ticklabel = uicontrol(...
                'Parent',obj.panel,...
                'BackgroundColor',a.par.win_background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'tick label');

            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            item_size(1) = 0.5 * (obj.size(1) - item_pos(1) - 2*a.par.size_space);
            obj.objects.xticklabel = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String', {' '});

            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            obj.objects.yticklabel = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String', {' '});
            
            %% grid
            item_size = a.par.size_label;
            item_pos  = [   a.par.size_space...
                            item_pos(2) - a.par.size_space-a.par.size_label(2) ];
            obj.objects.grid = uicontrol(...
                'Parent',obj.panel,...
                'BackgroundColor',a.par.win_background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'grid');

            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            item_size(1) = 0.5 * (obj.size(1) - item_pos(1) - 2*a.par.size_space);
            obj.objects.xgrid = uicontrol(...
                'Parent',obj.panel,...
                'Style','popup',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String', {'off','on'});
            
            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            obj.objects.ygrid = uicontrol(...
                'Parent',obj.panel,...
                'Style','popup',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String', {'off','on'});
            
            %% lim
            item_size = a.par.size_label;
            item_pos =  [   a.par.size_space...
                            item_pos(2) - a.par.size_space-a.par.size_label(2) ];
            obj.objects.lim = uicontrol(...
                'Parent',obj.panel,...
                'BackgroundColor',a.par.win_background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'lim');

            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            item_size(1) = 0.5 * (obj.size(1) - item_pos(1) - 2*a.par.size_space);
            obj.objects.xlim = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size]);
            
            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            obj.objects.ylim = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size]);
            
            %% label
            item_size = a.par.size_label;
            item_pos =  [   a.par.size_space...
                            item_pos(2) - a.par.size_space-a.par.size_label(2) ];
            obj.objects.label = uicontrol(...
                'Parent',obj.panel,...
                'BackgroundColor',a.par.win_background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'label');

            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            item_size(1) = 0.5 * (obj.size(1) - item_pos(1) - 2*a.par.size_space);
            obj.objects.xlabel = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size]);
                        
            item_pos(1)  = item_pos(1) + item_size(1) + a.par.size_space;
            obj.objects.ylabel = uicontrol(...
                'Parent',obj.panel,...
                'Style','edit',...
                'Units','pixel',...
                'Position', [item_pos item_size]);
                        
        end
        
        %% reposition
        function reposition(obj,a)
            previous_height = a.gfx.colour.position(2);
            height          = previous_height - obj.size(2);
            obj.set_position([obj.position(1),height]);
        end
    end
end
