%  ANALYSIS internal script
fprintf('analysis_constructor_gui: \n');

%% WINDOW
obj.obj.window = figure(...
    'Color',obj.gui.background,...
    'Name','ANALYSIS',...
    'Units','pixels',...
    'Position',[obj.gui.position,obj.gui.size],...
    'MenuBar','no',...
    'Resize','off',...
    'CloseRequestFcn',@obj.destructor);

%% TITLE
% title
panel_pos = [   obj.gui.space ...
                obj.gui.size(2)-obj.gui.space-obj.gui.title(2)];
panel_size = [  obj.gui.size(1)-2*obj.gui.space ...
                obj.gui.title(2) ];
uicontrol(...
    'Parent',obj.obj.window,...
    'BackgroundColor',obj.gui.background,...
    'Style','text',...
    'Units','pixel',...
    'Position', [panel_pos panel_size],...
    'String', ' ANALYSIS ');

%% FIGURE
% figure panel
panel_size(2) = obj.gui.labels(2) + obj.gui.figurebutton(2) + 2*obj.gui.space_figure;
panel_pos(2) = panel_pos(2)-panel_size(2)-obj.gui.space;
obj.obj.figure = uipanel(...
    'Parent',obj.obj.window,...
    'Title',' FIGURE ',...
    'BackgroundColor',obj.gui.background,...
    'Units','pixels',...
    'Position',[panel_pos panel_size]);

% figure popup list
item_pos =  [   obj.gui.space_figure...
            obj.gui.space_figure ];
item_size = [   panel_size(1)-3*obj.gui.space_figure-obj.gui.figurebutton(1)...
            obj.gui.figurebutton(2) ];
obj.obj.figure_list = uicontrol(...
    'Parent',obj.obj.figure,...
    'Style','popup',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'String',{' new figure'},...
    'Callback', @obj.figure_current);

% hold toggle button
item_pos = [item_pos(1)+item_size(1)+obj.gui.space_figure item_pos(2)];
item_size = obj.gui.figurebutton;
obj.obj.figure_hold = uicontrol(...
    'Parent',obj.obj.figure,...
    'Style','togglebutton',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'Visible','on',...
    'String','hold');

%% SDATA
% sdata panel
panel_size(2) = obj.gui.labels(2) + obj.gui.sdatabutton(2) + 2*obj.gui.space_sdata;
panel_pos(2) = panel_pos(2)-panel_size(2)-obj.gui.space;
obj.obj.sdata = uipanel(...
    'Parent',obj.obj.window,...
    'Title',' SDATA ',...
    'BackgroundColor',obj.gui.background,...
    'Units','pixels',...
    'Position',[panel_pos panel_size]);

% sdata popup list
item_pos =  [   obj.gui.space_sdata...
                obj.gui.space_sdata];
item_size = [   panel_size(1)-3*obj.gui.space_sdata-obj.gui.sdatabutton(1)...
                obj.gui.sdatabutton(2) ];
obj.obj.sdata_list = uicontrol(...
    'Parent',obj.obj.sdata,...
    'Style','popup',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'String',who(),...
    'Callback', @obj.set_opt_sdata_current);

% refresh button
item_pos = [item_pos(1)+item_size(1)+obj.gui.space_sdata item_pos(2)];
item_size = obj.gui.sdatabutton;
obj.obj.sdata_refresh = uicontrol(...
    'Parent',obj.obj.sdata,...
    'Style','pushbutton',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'Visible','on',...
    'String','refresh');

%% PLOT
% plot panel
panel_size(2) = obj.gui.labels(2) + 4*obj.gui.space_plot + 3*obj.gui.plotlistbox(2);
panel_pos(2) = panel_pos(2)-panel_size(2)-obj.gui.space;
obj.obj.plot = uipanel(...
    'Parent',obj.obj.window,...
    'BackgroundColor',obj.gui.background,...
    'Title',' PLOT ',...
    'Units','pixel',...
    'Position',[panel_pos panel_size]);

% x label
item_size = obj.gui.plotlabel;
item_pos =  [   obj.gui.space_plot...
            panel_size(2) - 2*obj.gui.space_plot - item_size(2) ];
obj.obj.plot_xbutton = uicontrol(...
    'Parent',obj.obj.plot,...
    'BackgroundColor',obj.gui.background,...
    'Style','text',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'HorizontalAlignment','left',...
    'String', 'x');
item_pos(1) = item_pos(1) + item_size(1) + obj.gui.space;
item_size(1) = panel_size(1) - 4*obj.gui.space_plot - obj.gui.plotpushbutton(1) - obj.gui.plotlabel(2);

% x expression entry textbox
obj.obj.plot_xtext = uicontrol(...
    'Parent',obj.obj.plot,...
    'BackgroundColor',obj.gui.background,...
    'Style','edit',...
    'Units','pixel',...
    'HorizontalAlignment','left',...
    'Position', [item_pos item_size]);

% y label
item_size = obj.gui.plotlabel;
item_pos(1) = obj.gui.space_plot;
item_pos(2) = item_pos(2) - obj.gui.space_plot-obj.gui.plotlabel(2);
obj.obj.plot_ybutton = uicontrol(...
    'Parent',obj.obj.plot,...
    'BackgroundColor',obj.gui.background,...
    'Style','pushbutton',...
    'Enable','off',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'HorizontalAlignment','left',...
    'String', 'y');
item_pos(1) = item_pos(1) + item_size(1) + obj.gui.space;
item_size(1) = panel_size(1) - 4*obj.gui.space_plot - obj.gui.plotpushbutton(1) - obj.gui.plotlabel(2);

% y expression entry textbox
obj.obj.plot_ytext = uicontrol(...
    'Parent',obj.obj.plot,...
    'BackgroundColor',obj.gui.background,...
    'Style','edit',...
    'Units','pixel',...
    'HorizontalAlignment','left',...
    'Position', [item_pos item_size]);

%% FLAGS

%% EXPORT
% export panel
panel_size(2) = obj.gui.labels(2) + obj.gui.exportbutton(2) + 2*obj.gui.space_export;
panel_pos(2) = panel_pos(2)-panel_size(2)-obj.gui.space;
obj.obj.export = uipanel(...
    'Parent',obj.obj.window,...
    'Title',' EXPORT ',...
    'BackgroundColor',obj.gui.background,...
    'Units','pixels',...
    'Position',[panel_pos panel_size]);

% export popup list
item_pos =  [   obj.gui.space_export...
            obj.gui.space_export];
item_size = [   panel_size(1)-3*obj.gui.space_export-obj.gui.exportbutton(1)...
            obj.gui.exportbutton(2) ];
obj.obj.export_list = uicontrol(...
    'Parent',obj.obj.export,...
    'Style','popup',...
    'Units','pixel',...
    'Position', [item_pos item_size],...
    'String',who(),...
    'Callback', @obj.set_opt_export_current);

%% SAVE / LOAD

