classdef analysis < handle
    % class for analyse the data
    
    properties
        gui
        obj
        opt
    end
    
    methods
        %% constructor
        function obj = analysis(sdata)
            % gui parameters
            obj.gui = struct();
            obj.gui.background = [.8 .8 .8];
            obj.gui.position = [0,0];
            obj.gui.size = [350,950];
            
            obj.gui.title           = [nan,15];
            obj.gui.labels          = [nan,10];
            obj.gui.figurebutton    = [40,24];
            obj.gui.plotlistbox     = [nan,100];
            obj.gui.plotlabel       = [40,24];
            obj.gui.plotpushutton   = [40,24];
            obj.gui.plotcheckbox    = [24,24];
            obj.gui.plotpushbutton   = [24,40];
            
            obj.gui.space = 10;
            obj.gui.space_figure = 7.5;
            obj.gui.space_plot = 7.5;
            
            %% gui objects
            obj.obj = struct();
            
            %% options
            obj.opt = struct();
            obj.opt.figure_curvecolor = { ...
                [0 0 1], ... b
                [0 1 0], ... g
                [1 0 0], ... r
                [0 1 1], ... c
                [1 0 1], ... m
                [1 1 0], ... y
                [0 0 0], ... k
                };
            obj.opt.figure_figures = [];
            
            %% gui start
            obj.gui_start();
        end
        
        %% draw the gui
        function obj = gui_start(obj)
            %% WINDOW
            obj.obj.window = figure(...
                'Color',obj.gui.background,...
                'Name','analysis user interface',...
                'Units','pixels',...
                'Position',[obj.gui.position,obj.gui.size],...
                'MenuBar','no',...
                'Resize','off',...
                'CloseRequestFcn',@obj.closed_window...
            );
            
            % TITLE
            % title
            panel_pos = [   obj.gui.space ...
                            obj.gui.size(2)-obj.gui.space-obj.gui.title(2)];
            panel_size = [  obj.gui.size(1)-2*obj.gui.space ...
                            obj.gui.title(2) ];
            uicontrol(...
                'Parent',obj.obj.window,...
                'BackgroundColor',obj.gui.background,...
                'Style','text',...
                'Units','pixel',...
                'Position', [panel_pos panel_size],...
                'String', ' analysis user interface');
            
            %% FIGURE
            % figure panel
            panel_size(2) = obj.gui.labels(2) + obj.gui.figurebutton(2) + 2*obj.gui.space_figure;
            panel_pos(2) = panel_pos(2)-panel_size(2)-obj.gui.space;
            obj.obj.figure = uipanel(...
                'Parent',obj.obj.window,...
                'Title',' figure ',...
                'BackgroundColor',obj.gui.background,...
                'Units','pixels',...
                'Position',[panel_pos panel_size]...
            );
            % figure popup list
            item_pos =  [   obj.gui.space_figure...
                            obj.gui.space_figure ];
            item_size = [   panel_size(1)-3*obj.gui.space_figure-obj.gui.figurebutton(1)...
                            obj.gui.figurebutton(2) ];
            obj.obj.figure_list = uicontrol(...
                'Parent',obj.obj.figure,...
                'Style','popup',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'String',{' new figure'},...
                'Callback', @obj.set_opt_figure_current...
            );
            % hold toggle button
            item_pos = [item_pos(1)+item_size(1)+obj.gui.space_figure item_pos(2)];
            item_size = obj.gui.figurebutton;
            obj.obj.figure_hold = uicontrol(...
                'Parent',obj.obj.figure,...
                'Style','togglebutton',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'Visible','on',...
                'String','hold'...
            );
            
            %% PLOT
            % plot panel
            panel_size(2) = obj.gui.labels(2) + 4*obj.gui.space_plot + 3*obj.gui.plotlistbox(2);
            panel_pos(2) = panel_pos(2)-panel_size(2)-obj.gui.space;
            obj.obj.plot = uipanel(...
                'Parent',obj.obj.window,...
                'BackgroundColor',obj.gui.background,...
                'Title',' plot ',...
                'Units','pixel',...
                'Position',[panel_pos panel_size]);
            
            % x label
            item_size = obj.gui.plotlabel;
            item_pos =  [   obj.gui.space_plot...
                            panel_size(2) - 2*obj.gui.space_plot - item_size(2) ];
            obj.obj.plot_xbutton = uicontrol(...
                'Parent',obj.obj.plot,...
                'BackgroundColor',obj.gui.background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'x' ...
            );
            item_pos(1) = item_pos(1) + item_size(1) + obj.gui.space;
            item_size(1) = panel_size(1) - 4*obj.gui.space_plot - obj.gui.plotpushbutton(1) - obj.gui.plotlabel(2);
            % x expression entry textbox
            obj.obj.plot_xtext = uicontrol(...
                'Parent',obj.obj.plot,...
                'BackgroundColor',obj.gui.background,...
                'Style','edit',...
                'Units','pixel',...
                'HorizontalAlignment','left',...
                'Position', [item_pos item_size]...
            );
            % y label
            item_size = obj.gui.plotlabel;
            item_pos(1) = obj.gui.space_plot;
            item_pos(2) = item_pos(2) - obj.gui.space_plot-obj.gui.plotlabel(2);
            obj.obj.plot_ybutton = uicontrol(...
                'Parent',obj.obj.plot,...
                'BackgroundColor',obj.gui.background,...
                'Style','pushbutton',...
                'Enable','off',...
                'Units','pixel',...
                'Position', [item_pos item_size],...
                'HorizontalAlignment','left',...
                'String', 'y' ...
            );
            item_pos(1) = item_pos(1) + item_size(1) + obj.gui.space;
            item_size(1) = panel_size(1) - 4*obj.gui.space_plot - obj.gui.plotpushbutton(1) - obj.gui.plotlabel(2);
            % y expression entry textbox
            obj.obj.plot_ytext = uicontrol(...
                'Parent',obj.obj.plot,...
                'BackgroundColor',obj.gui.background,...
                'Style','edit',...
                'Units','pixel',...
                'HorizontalAlignment','left',...
                'Position', [item_pos item_size]...
            );
        end
        
        function obj = closed_window(obj,gui_obj,~)
            % figures
            for h_fig = obj.opt.figure_figures
                delete(h_fig);
            end
            % window
            delete(gui_obj);
            delete(obj);
        end
    end
end